# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FtmYM5uTXaYVDJdAKFaKWVbiDLU7GdrnnpOZT9oe5vzbXuFTXprXDBHecSaEg/DNwNsWTd14wcx9TxuWavyVVVhHQeboZWeZs55ZvHbui60TiwgX8q7axZMjAdMNOSAv6a7h25g4Qx2xOGmc3MH2NxvXq5XOcQ75VqkuXCLC0WADtomX4pVTlGLGueyaMSQ/7o3EVWRuM7NNs0mnHi0adWOVb7lt9IMxrwEWskDbJ1QytwzrAlvBrUJVpiDUyWSpIg/33jnzxXGoWeUWefM1cTB5IJOTEAgIYaMqFcTjcP/buN2677pDSUTf2ua0XNpBhHvwdnDs6mHFZEz5iRD5OXA4LJFEI6y2xEutUopOAptJh+HQV+A48TLgBLpO4NYi+qFLkGv56CB++JHyl7pz+UbRiQBl1Acaa0DAfI9Shg48PL9w6l0/Dh80y54kRVntZ/gotUxRMOPp6gbP+Y2eRou6dCkdz1XCNYjTWxWBInCeZ6Jy2uDP2N2JAkaGIZKcHDzajdW/WCbALf4i4Netf9tWlsXn965+UJSxgKDqhOmH89koKFwGa7X1yPBmhIlxJzs5lnpqjVF1+GeedJfqC01LmsKdi3trmwCHn4c20TXBDZFOmu8VYtQbEFLAbggzP8+x4pMncaIcIUQyFYEoxiTaJLrPS99UJgadx24nK3w="

matrix:
  include:
    - env: CONFIG=linux_ UPLOAD_PACKAGES=True PLATFORM=linux-64 DOCKER_IMAGE=condaforge/linux-anvil-comp7
      os: linux

    - env: CONFIG=osx_ UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:
  - export CI=travis

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi

  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.travis/run_docker_build.sh; fi