github:
  user_or_org: lantzproject
channels:
  sources:
  - conda-forge
  - hgrecco
  - defaults
  targets:
  - [hgrecco, main]
provider:
  linux: travis
  osx: travis
  win: appveyor
  linux_ppc64le: None
  linux_aarch64: None
min_py_ver: '36'
travis:
  secure:
    BINSTAR_TOKEN: yI0iS1YyjpcnqDqw0dSRYccqoAydyymI0N2ZOv/qG4EnuZ9ICbypZkZyEmLWveIoRt1md5Tgfn5IKxIb60jF/gHxllwQanzZ35OEutWhuuhX5JLnMv8bosCKD1qYGPUQwUfdfZliFC+F2k7978AAtqV84dh79u3DCo11GoX7zRpz5476bZXB/CAkSsJrYc3rrM9oQd4PZIRnCc1cv+i+KFvSZg0VIHEkZt/sUgR7G013s2peMb4q/bbzixdw/uCded+310gJhtsY4jtgvEVCXszkf7LDXf2ZtN+wjGCFikzwFGbv/3uBxVERZ+18Vi5yoeAOqsJQuho/TwVxWdAk3CxkK+hGqUZLOO9OY+aDBKo3MewsZG+LHHdc/7DwfyAcMvaduTPHXfkMMH7xBN+6NaW86t7aRrAImfKGiVSROeY0k/tXweWjuYRhjMBL8Mq4e2t8J3opTZ7xpCVM40ENO8TO48uv7mQJqGGcfUOcKu640aRSrbRyETBKewnp44nqplohHuzs1AlCtKoWNnybJbOqh+RA/QUy+yZaDaMIwLdmQyxnal6XZbXbuH/MyFSnSM9ACXGtfgYRBfv6jVMnMc5JVQkp277Hmf5QQAVqml0slQC43gASFzgu5OBMccqzHaY3xE+KDJaE2+o6EYMh/nGn0NEd5mO32dEweLS+5MQ=
appveyor:
  secure:
    BINSTAR_TOKEN: qnTwQiGJBWgaW8Tb+rS3SXRTxJPbZJrEtADGdVzCqFn9SEcoewAV3jA/KOhhunFy
