github:
  user_or_org: lantzproject
channels:
  sources:
  - conda-forge
  - hgrecco
  - defaults
  targets:
  - [hgrecco, main]
provider:
  linux: travis
  osx: travis
  win: appveyor
  linux_ppc64le: None
  linux_aarch64: None
min_py_ver: '36'
travis:
  secure:
    BINSTAR_TOKEN: Sz3LtIO3r4NCJbmjkJihqrDnr0uEY5G5bNrN0riCN/PMyVwDkABUiAutNDomi/eL4c0E+D3018FlD+Aj9Kz+fvBhP1gMz3gWVgaxVtv9kjVLYIYCD1EiCFZH0qVQDlDLmruD6/o1jtCjFUhGMcybbPUopXEQ3QCt+G/c2RXe62bLqn5LMV05a4LSRtxDiHvvjlVaNjXU2LD5O+VO2Ft3DL2AP+245Oqbuuoo5h87TanRPM6O46xQRGeJJeeIbb5UGJDQKOdfUJC/hgwNTYJGBmVNA5r9zV0kFgbhcDcC8np7SWLTADbbToj6g0odSa93Y4ihdyJkLOj3kkwl0QfrHavyfdIElSYqOaXOGxzxxIWb1eXBYdifMegpnUeF+WY2oLl55s+OXbmTQ8o9RPA0Ck62bnVZyXxEBj1SFJlV3RdvtkD/AvZVq++2nD901UhiMI/mqpTEd92P2e4Te2Cbtpi5ydj1GICxVV/nziBZKULBEBwZKmbZweFUHIz+hurKzO5q7Uw2nkPia2KRtmtIpfc/Rgg3fx57rVxCGgoDZ0AofYbAVDARJzPinkSB5XIMikVN2BLjFUp6pb6NsYOGIQXhd0uYvqJ7cuaamo14gfq5xguE1ZoXUkpGRa+j42GROErrORmnyXQugZBkO6n85lff74yUoPwxqAHUfHtehRY=
appveyor:
  secure:
    BINSTAR_TOKEN: qnTwQiGJBWgaW8Tb+rS3SXRTxJPbZJrEtADGdVzCqFn9SEcoewAV3jA/KOhhunFy
