github:
  user_or_org: lantzproject
channels:
  sources:
  - conda-forge
  - hgrecco
  - defaults
  targets:
  - [hgrecco, main]
provider:
  linux: travis
  osx: travis
  win: appveyor
  linux_ppc64le: None
  linux_aarch64: None
min_py_ver: '36'
travis:
  secure:
    BINSTAR_TOKEN: ZK31nernJ9yapxWVXpcu0pRFHO3SEbGZyMqZQxY1VAMfWhGTHMiifg169ph/oZsDtNoBtbJjp4KNRyCyt+r1O+dvtKFdwrPanGxrCOiuPHQ5DRnkPut+scuY7BPrQgZjw82hROYFd3UOoaqu9/EpMui8CxqDNUjcAbBaXR2zDZzUV2cSb90pudevA2UfEHI48abSX9Fj7DjPNMW9/2aY1APMMnm7CyHKW76Wj7qe2+QlPddWqFKNeh/p6eDfkIEE9HORaGK32uUwJeOyltiUyyXjnpSzloNqKFMWbSV1dY+ExNXnfQYBEHo1NCNlXjTLlVKIHOwYCwXatscI2NZm1Cbk+yB/76FW2P/7SjKI/UQIbnTMmy2WnksPq0eJ/8O0TL+UZ7ik+QxIociULKYdpMMzAZbQFk5eMoqD4MSedgnpxZ+yfmqaoITF+QDgy6QUZoEDEyB2bTnBlu3PVOLGAjO62vgpUdfLxCJtbJ9p2DZPLzEqYUy6gFpHYWqn2RZY8zIgqyV26eIhK6wN/kjLiSAc822qk85kUUYCk3U/8g9vtzXylIbQtwSTC3LYgxLKwvd6mhgsEIw23jMHD1A6des4Ke0bBUHe39dcz5J6XM6ZBLIZK5tns2fCR6kS8m7vzB1RRYvakU4wy0ZDJnr4/V+eB/nTcZwNUl7fexkkfzE=
appveyor:
  secure:
    BINSTAR_TOKEN: qnTwQiGJBWgaW8Tb+rS3SXRTxJPbZJrEtADGdVzCqFn9SEcoewAV3jA/KOhhunFy
